services:
 
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: monit-prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
 
  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: monit-alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 9093:9093
    restart: always
 
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: monit-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always

  fastapi:
    build:
      context: .
    container_name: monit-fastapi
    ports:
    - 8000:8000
    restart: always
    env_file:
    - .env