apiVersion: v1
kind: Pod
metadata:
  name: multiple-containers
  namespace: default
spec:
  containers:
  - image: busybox:latest
    command:
    - sleep
    args:
    - '3600'
    name: busybox
  - image: nginx
    name: nginx